### ISSUE TITLE
Portable ssh and gpg.

### ISSUE THREAD

**Issue by JosiasVasquez** [uroesch/GitPortable#114]
Hello, I'm trying connect to github, but git portable don't recognize the ssh command.
Can you please configure ssh and gpg to start automatically together git, also save and search the keys in the portable directory instead the user profile folder.
Thanks

**Comment by uroesch** [comment]
Hello, 
Thanks for using GitPorrable and the report in particular. 

Do you mind sending me information about your environment.
* OS Version
* Git Portable Version (find out with command `git --version`)
* Which terminal are you (mintty with bash or terminal with cmd)
* Can you send the error message you are getting if any.

Also let me know if you have setup a ssh public key in GitHub and if the private ssh key is stored under `${HOME}/.ssh/id_rsa` or `${HOME}/.ssh/id_ed25519`

As a reference I just checked on my end with a Windows 10 installation using git version 2.35.1.windows.2 under mintty with bash.
```console 
urs@Roadrunner-PC MINGW32 ~/.ssh
$ ls -ltra
total 11
-rw-r--r-- 1 urs 197121 168 Feb  9 08:37 known_hosts.old
drwxr-xr-x 1 urs 197121   0 Feb  9 08:37 ../
-rw-r--r-- 1 urs 197121 556 Feb  9 08:38 known_hosts
drwxr-xr-x 1 urs 197121   0 Feb  9 08:40 ./
-rw-r--r-- 1 urs 197121 464 Feb  9 08:40 id_ed25519

urs@Roadrunner-PC MINGW32 ~/.ssh
$ git clone git@github.com:uroesch/GitPortable.git
Cloning into 'GitPortable'...
The authenticity of host 'github.com (140.82.121.3)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
Enter passphrase for key '/c/Users/urs/.ssh/id_ed25519':
remote: Enumerating objects: 848, done.
remote: Counting objects: 100% (399/399), done.
remote: Compressing objects: 100% (230/230), done.
remote: Total 848 (delta 195), reused 265 (delta 128), pack-reused 449
Receiving objects: 100% (848/848), 417.09 KiB | 3.50 MiB/s, done.
Resolving deltas: 100% (382/382), done.
```
cheers, 

--urs

**Comment by JosiasVasquez** [comment]
hello, 
I'm using git version 2.35.1.windows.2 OS windows 11.
Edición	Windows 11 Home Single Language
Version	21H2
with git CMD when I try to generate a ssh key this is the message.
"ssh" don't recognize as a internal or external command.
program or batch file executable.
Something like that, because the message I got in Spanish.
The same message I get when I try to generate a gpg key.
I was able to generate a ssh key executing the start-ssh-agent.cmd file on the cmd folder.
I was try to execute the start-ssh-pageant.cmd on the same folder but it don't open the console.
the git portable I installed with the portable executable file. I do not clone the repository.
When I try to push something to github this try to conect with the ssh keys on my user folder on the the users folder. but finally I get  an error.

${HOME}/.ssh/id_ed25519

**Comment by uroesch** [comment]
Hello Josias, 

Thanks for the detailed information I will try to reproduce the problem on my Windows 11 host and get back to you shortly.

cheers, 

--urs

**Comment by uroesch** [comment]
Hello Josias

I had a look at your issue and must file this as a problem which is present in upstream. I did download another release and tested both on Windows 10 and Windows 11. The result was the same. For some reason the Windows Terminal when started via `git-cmd.exe` can not see the directory `C:\Windows\System32\OpenSSH` althought it is set in the `%PATH%`. I don't know if this is done deliberately by the developers of the upstram git-for-windows project or if we look at a Windows internal security mechanism. 

Now that said. I have a few solutions ready as workaround. And I documented them in the README. https://github.com/uroesch/GitPortable#ssh-key-setup

As a solution:

1. Use `Git Bash` which is generally the default. It bundles all the Unix tools that are for the most part essential for working with Git. As [documented](https://github.com/uroesch/GitPortable#git-bash) you can create and manage ssh keys without trouble under `git-bash`. 
2. Create the key under `git-bash` or in a separate CMD or PowerShell terminal where the Windows internal ssh commands work. The use the [instructions] (https://github.com/uroesch/GitPortable#git-cmd) to use the keys with the ssh-agents at hand.

BTW - The instructions are based on the new release v2.35.1.2-beta6-uroesch

cheers, 

--urs

**Comment by JosiasVasquez** [comment]
Ok, Yes by now, I will use git bash, but I'm a visual impaired people, and I use a screen reader NVDA, the git bash NVDA don't read when I try to read by character.
This is the only reason I use git CMD.

**Comment by JosiasVasquez** [comment]
Thanks for your effort

**Comment by uroesch** [comment]
Thanks for the feedback. 

As I mentioned you may also be able to use a plain vanilla Windows terminal to generate the key or us PuTTY as an alternative SSH Key provider if that is more suitable for your needs. Once the key is in place you are free to use Git CMD without any restrictions as far as I can tell.

**Comment by JosiasVasquez** [comment]
Ok, thanks, I will download and try to use.

**Comment by uroesch** [comment]
Good news. I found a workaround for the issue. I will wrap a new release and post a link here shortly.

**Comment by uroesch** [comment]
You may download a fixed version from https://github.com/uroesch/GitPortable/releases/tag/v2.35.1.2-beta8-uroesch
With this release the ssh command and ssh-keygen is showing is found in the path.

**Comment by JosiasVasquez** [comment]
Thanks a lot, for all your work.
Its very useful for me.

**Comment by JosiasVasquez** [comment]
Hi, just writing to confirm that everything is working great now.

**Comment by uroesch** [comment]
Thanks for the feedback and apologies for sending you down the wrong path in the first place. I was looking in all the wrong places in the beginning.
 
I'm so glad I could fix the problem and put you on your path to a happy git life :).

**Comment by JosiasVasquez** [comment]
I love the portable apps, and I had a lot of problems with the portable git, but now, all is ok. thanks you!
